apiVersion: v1
kind: Service
metadata:
  name: print-character-service
spec:
  selector:
    app: print-character
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-character
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-character
  template:
    metadata:
      labels:
        app: print-character
    spec:
      containers:
        - name: print-character
          image: tuannguyen1999xxx/test_print_arm:latest
#          command: [ "/bin/bash", "-c", "--" ]
#          args: [ "while true; do sleep 300; done;" ]
          ports:
            - containerPort: 8000

