apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app.kubernetes.io/name: deepstream
  name: deepstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deepstream
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deepstream
    spec:
      containers:
      - args:
        - -c
        - /opt/nvidia/deepstream/deepstream-5.0/samples/configs/deepstream-app/source4_1080p_dec_infer-resnet_tracker_sgie_tiled_display_int8.txt
        command:
        - deepstream-app
        image: nvcr.io/nvidia/deepstream-l4t:5.0-dp-20.04-samples
        imagePullPolicy: IfNotPresent
        name: deepstream
        ports:
        - containerPort: 8554
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/nvidia/deepstream/deepstream-5.0/samples/configs/deepstream-app/source4_1080p_dec_infer-resnet_tracker_sgie_tiled_display_int8.txt
          name: ipmount
          subPath: source4_1080p_dec_infer-resnet_tracker_sgie_tiled_display_int8.txt
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nvidia-registrykey-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      volumes:
      - configMap:
          defaultMode: 420
          name: deepstream-configmap
        name: ipmount
